name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2

  # ไอคอนมาตรฐาน
  cupertino_icons: ^1.0.8

  # ตัวเชื่อมต่อ database (Postgres)
  postgres: ^3.5.9
  supabase_flutter: ^2.12.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.1
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  get: ^4.7.3
  google_fonts: ^8.0.1
  cloud_firestore: ^6.1.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  dio: ^5.9.0
  curved_navigation_bar: ^1.0.6
  uuid: ^4.5.1
  grouped_list: ^6.0.0
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
